### ISSUE TITLE
pixelgrab crashes sometimes

### ISSUE THREAD

**Issue by craig** [danrl/pixelgrab#1]
```
$ ./pixelgrab
panic: runtime error: index out of range

goroutine 22 [running]:
main.run.func2(0xc0003b6080, 0xc0000, 0xc000534000, 0xc0000, 0xe2000)
	/home/danrl/.hacked/main.go:108 +0x36e
created by main.run
	/home/danrl/.hacked/main.go:74 +0x3ca

```

**Comment by kordianbruck** [comment]
I guess its fixed? ¯\_(ツ)_/¯

**Comment by danrl** [comment]
Woopsie 🍡
